version: '3.3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"